# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/versions.html
minecraft_version=26.1.2
loader_version=0.18.4
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version = 2.1
maven_group = de.domiirl
archives_base_name = morebannerfeatures

# Dependencies
fabric_version=0.150.0+26.1.2
modmenu_version=18.0.0-beta.1
trinkets_version=3.11.0-1.21.6
cca_version=7.1.0-beta.1
accessories_version=1.2.19-beta+1.21.4
